site_name: 2020_5CI_Team5
nav:
    - 'Project Charter': 'Project Charter Doc.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management plan': 'Software Project Management Plan.md'
    - 'Business Model Canvas pdf': 'pdf version/business_model_canvas_poster.pdf'
  
    
theme:
    name: readthedocs

use_directory_urls: true
