site_name: 2020_5CI_Team5
nav:
    - 'Project Charter': 'Project Charter Doc.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management plan': 'Software Project Management Plan.md'
    - 'Business Model Canvas pdf': 'business_model_canvas.pdf'
    - 'Release Plan': 'Release Plan.md'
    - 'Iteration Plan': 'Iteration Plan.md'
    - 'Project Success Criteria': 'Project Success Criteria.md'
    - 'Architecture and Design': 'Architecture and Design.md'
    - 'Test Plan': 'TestPlan.md'
    - 'Test Case Specification': 'Test Case Specification.md'
    - 'User Guide': 'User guide.md'
    - 'System Documentation': 'System Documentation.md'
    - 'Architecture and Design': 'Architecture and Design.pdf'
    - 'DPA-model-English': 'DPA-model-English.pdf'
    - 'Iteration Plan': 'Iteration Plan.pdf'
    - 'Project Success Criteria': 'Project Success Criteria.pdf'
    - 'Release Plan': 'Release Plan.pdf'
    - 'System Documentation': 'System Documentation FINITO.pdf'
    - 'Test Case Specification': 'Test Case Specification.pdf'
    - 'Test Plan': 'Test Plan.pdf'
    - 'User Guide': 'User Guide.pdf'
  
    
theme:
    name: readthedocs

use_directory_urls: true
